services:
  api:
    build: .
    command: python api_server.py
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
