services:
  api:
    build:
      context: ./prover9-mace4-api
      dockerfile: Dockerfile
    command: python api_server.py --production --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  gui:
    build:
      context: ./prover9-mace4-gui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped 