services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python api_server.py --production --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped