services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python api_server.py
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - ../Samples:/app/Samples

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - PROVER9_API_URL=http://localhost:8000
    restart: unless-stopped 